name: TechKits
version: '${version}'
main: me.thelpro.techkits.TechKits
commands:
  kit:
    description: "Kit command"
    permission: techkits.kit.use
permissions:
  techkits.kit.use:
    description: Use /kit
    default: not op